version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[skip ci]"
    groups:
      trpc:
        patterns:
          - "@trpc/*"
      codegen:
        patterns:
          - "@graphql-codegen/*"
      rtl:
        patterns:
          - "@testing-library/*"

