"App: Data Importer": "apps/data-importer/**/*"
"App: Invoices": "apps/invoices/**/*"
"App: Klaviyo": "apps/klaviyo/**/*"
"App: Product Feed": "apps/products-feed/**/*"
"App: Search": "apps/search/**/*"
"App: Slack": "apps/slack/**/*"
"App: Taxes": "apps/taxes/**/*"
"App: Avatax": "apps/avatax/**/*"
"App: Taxjar": "apps/taxjar/**/*"
"App: Emails & Messages": "apps/emails-and-messages/**/*"
"App: CMS": "apps/cms-v2/**/*"
"App: CRM": "apps/crm/**/*"
"App: Segment": "apps/segment/**/*"
