name: Run tests

on:
  pull_request:

jobs:
  unit_test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Generate schema
        run: pnpm generate
      - name: Test
        run: pnpm test
# TODO: Add coverage - crawl through every package
#      - name: Generate coverage report
#        uses: irongut/CodeCoverageSummary@v1.3.0
#        with:
#          filename: coverage/cobertura-coverage.xml
#          format: markdown
#          output: file
#
#      - name: Add Coverage PR Comment
#        uses: marocchino/sticky-pull-request-comment@v2
#        if: github.event_name == 'pull_request'
#        with:
#          recreate: true
#          path: code-coverage-results.md